### ISSUE TITLE
User manual?

### ISSUE THREAD

**Issue by dolmen** [keith-packard/snekboard#1]
I received my SnekBoard via CrowSupply, but what now? I see a blue button, but what does it do? LEDs change color when I push the blue button, but what do they mean?

The only information I found is this: https://sneklang.org/doc/snek.html#_snek_on_snekboard

**Comment by keith-packard** [comment]
Glad it arrived safely!

There are also some sample lessons using snekboard available at
sneklang.org:

https://sneklang.org/docs/

That uses a snek-compatible version of 'mu' editor, instructions for
getting that installed are available here:

https://sneklang.org/mu/

The snek language manual includes a tutorial that doesn't involve
connecting anything up, if you want to explore the language:

https://sneklang.org/doc/snek.html#_a_gentle_snek_tutorial

If you're interested in exploring CircuitPython, you can check out the
snekboard page for that language here:

https://circuitpython.org/board/snekboard/

The blue button is the 'reset' button. Press it once and snekboard will reboot. Press it twice and snekboard will switch to 'boot loader' mode where it appears as a USB storage device. Plug that into your laptop when you want to install a new version of Snek, or switch between Snek and Circuit Python.
